### ISSUE TITLE
Price gap between historical dataset and live API requests

### ISSUE THREAD

**Issue by mvrozanti** [samre12/deep-trading-agent#1]
For kaggle's btceUSD dataset we got these last 5 lines in which BTC(USD) weighted price =2130~2139:

    1496188560,2130,2130,2129.999,2129.999,2.35330472,5012.53827,2129.999667
    1496188620,2130,2134.8,2130,2134.8,12.03238662,25648.897767,2131.6550554
    1496188680,2133.2,2134.8,2133.2,2134.8,1.40799439,3005.4756141,2134.5792536
    1496188740,2134.8,2143.79,2134.8,2134.801,3.19062001,6824.2637131,2138.8519133
    1496188800,2139.999,2140,2134.35,2139.999,6.73707917,14413.324651,2139.4025938

When I make a request to [cryptocompare](https://min-api.cryptocompare.com/) website for BTC(USD) I get this where the price suddenly jumps to 7656.98 USD at the same timestamp:

`{"RAW":{"BTC":{"USD":{"TYPE":"5","MARKET":"CCCAGG","FROMSYMBOL":"BTC","TOSYMBOL":"USD","FLAGS":"1","PRICE":7656.98,"LASTUPDATE":1511013600,"LASTVOLUME":0.26175057,"LASTVOLUMETO":2002.3918605000001,"LASTTRADEID":"26754557","VOLUMEDAY":48775.74066467763,"VOLUMEDAYTO":372532531.85840243,"VOLUME24HOUR":89903.71924385922,"VOLUME24HOURTO":693640577.3317167,"OPENDAY":7699.95,"HIGHDAY":7798.12,"LOWDAY":7458.9,"OPEN24HOUR":7829.71,"HIGH24HOUR":7982.5,"LOW24HOUR":7446.1,"LASTMARKET":"Bitstamp","CHANGE24HOUR":-172.73000000000047,"CHANGEPCT24HOUR":-2.2060842611029075,"CHANGEDAY":-42.970000000000255,"CHANGEPCTDAY":-0.5580555717894304,"SUPPLY":16686375,"MKTCAP":127767239647.5,"TOTALVOLUME24H":480649.677315126,"TOTALVOLUME24HTO":3685574563.3642445}}}`

What am I missing here sir?

**Comment by samre12** [comment]
@mvrozanti please take a note of the timestamps of the prices of the Bitcoin mentioned in the two sources. The last timestamp in dataset obtained from Kaggle corresponds to 30th May 2017 at which time around the price of Bitcoin was 2100$.
[Cyrptocompare](https://www.cryptocompare.com/) gives live prices of Bitcoin. In fact the query that you mentioned corresponds to 18th November and currently the price of Bitcoin is above 8000$.

**Comment by samre12** [comment]
@mvrozanti please close this issue if you think it is resolved. 😺

**Comment by mvrozanti** [comment]
Oh shit you're right thanks mate

**Comment by samre12** [comment]
Sure mate. 👍
