### ISSUE TITLE
not an issue - fyi dockerfile + ssh daemon

### ISSUE THREAD

**Issue by johndpope** [samre12/deep-trading-agent#10]
https://gist.github.com/johndpope/b8a1f334e1d1769e73391ad6270bbff9

for easier config editing. 
![screen shot 2018-05-07 at 15 27 20](https://user-images.githubusercontent.com/289994/39720673-2a7bd27c-520b-11e8-9f2b-307c5ad396e1.png)

**Comment by samre12** [comment]
@johndpope thanks for the update. I will surely consider this in the next commit to the master. 
Cheers 😄
