### ISSUE TITLE
Why On Earth would you use python 2.7 ? that's backward 

### ISSUE THREAD

**Issue by developeralgo8888** [samre12/deep-trading-agent#11]
Why On Earth would you use python 2.7 ? that completely makes no sense but anyway good project

**Comment by samre12** [comment]
I don't believe that in the context of this project because the code mainly comprises of `numpy` and `tensorflow` which provide alike api for both python2 and python3.
It would be highly appreciated if you raise a pull request for a python3 version of the project 😄.

**Comment by johndpope** [comment]
it's possible at command line to simply type
`**2to3 */*.py -W** `
this will upgrade syntax in files to python3.

**Comment by johndpope** [comment]
https://github.com/hocgabri/deep-trading-agent/commit/2f06439cbfa76a71e39ddd39df2e90d3ca338cf3
