### ISSUE TITLE
enhancement - risk reward / position sizing

### ISSUE THREAD

**Issue by johndpope** [samre12/deep-trading-agent#12]
it seems without a sense of risk / reward or position sizing - the trained model is a glorified heads + tails flip calculator based off previous data.
 
it maybe beyond scope of project - but to build an autonomous agent  that can a variety of actions - need to somehow incorporate this to win the trading game. Perhaps there's two trained models. 

https://github.com/m-esgana/poor-trader-py/blob/097fbb10c217abe0db5a2cd55d73e0ad2990acd9/poor_trader/trading.py

**Comment by samre12** [comment]
Surely gonna look into it 😄

**Comment by johndpope** [comment]
I'm doing a spring clean on older github issues - going to close this.
