### ISSUE TITLE
Add trading activity as an input

### ISSUE THREAD

**Issue by nanvel** [samre12/deep-trading-agent#17]
I am a very beginner in ML and so have little understanding on what this model capable of.
Only want to suggest and, hopefully, get a feedback.

If we analyze only raw exchange data, as trades in order books and closed ones, we may have:
- current buy and sell price
- buy and sell volumes in some period of time
- number of buy and sell orders closed  (they are not always correlated with volume)
- buy and sell order book (for example, volume needed to move price for particular percent, or measure activity in order book)

As post-processing of these values, we can divide them by SMA, measure speed they are changing.

**Comment by samre12** [comment]
@nanvel we can extend the input space for the model by adding all kinds information available from the exchange. But we need to keep 2 things in mind:
- the source of information that we are using should reliable
- we need to adapt to model in a way to optimally use the new information

Once, we can guarantee the above, we can proceed with the suggestion.
