### ISSUE TITLE
Testing module

### ISSUE THREAD

**Issue by lamhk** [samre12/deep-trading-agent#19]
Hi samre12,

After the training using the main.py, how can I test on another set of data?  Thanks.

Thanks,
Lam

**Comment by samre12** [comment]
Hi @lamhk , I haven't specifically made the testing module for agent. On the dev branch of the repository, I use [`samre12/gym-cryptotrading`](https://github.com/samre12/gym-cryptotrading) to train the agent which is [`Gym`](https://gym.openai.com) based environment to train the agent. 
`gym-cryptotrading` can be used for testing the agent learned using the current repository.

**Comment by samre12** [comment]
Just make sure that the same environment type and parameters are used to train and test the agent. 😄
