### ISSUE TITLE
ModuleNotFoundError: No module named 'ConfigParser'

### ISSUE THREAD

**Issue by philipshurpik** [samre12/deep-trading-agent#4]
Hi!  Tried to run your agent but found an error - "ModuleNotFoundError: No module named 'ConfigParser'" - seems that this file was not committed
ah, okay - it's python 2.7

**Comment by samre12** [comment]
Sure! 😄 
Hey! please checkout the dev branch of this repository. It contains recently updated code with improved model performance. It also provides docker support for running the code directly.

**Comment by philipshurpik** [comment]
thank you!   I will definitely look at it!
