### ISSUE TITLE
ERROR: No section: 'global'

### ISSUE THREAD

**Issue by cTatu** [samre12/deep-trading-agent#9]
Hello, I tried running the code with the config file shown in the image and I still getting that error. But the **`'global'`** section is at the beginning of the file.

![image](https://user-images.githubusercontent.com/37102803/39264049-25ba26da-48c4-11e8-9097-9bae73fb8674.png)

```
>sudo cat config/config.cfg
[global]
PARENT_DIR = /home/mmnkl9/deep-trading-agent/code/

[logging]
LOG_FILE = logs/run.log
SAVE_DIR = logs/saved_models/
TENSORBOARD_LOG_DIR = logs/tensorboard/

[preprocessing]
DATASET_PATH = data/btc.csv

[dataset]
BATCH_SIZE = 32
HISTORY_LENGTH = 180
```

**Comment by samre12** [comment]
Hi @cTatu , try providing the absolute path of the configuration file while running the code. If the problem still persists, let me know.

**Comment by cTatu** [comment]
Thanks for answering @samre12 , I also tried that but still get the same error. I thought that was reading another file but the folder only has that one file.

**Comment by samre12** [comment]
Hi @cTatu , I am still not able to understand the cause of the issue. I am not able to reproduce the problem on my system. Googling about the issue indicates a possible issue with `re` package. But still there might other causes for the same issue.

**Comment by hullyang** [comment]
I had the same issue, and I found that config.cfg file path was wrong. Hope this would help you.

**Comment by samre12** [comment]
@hullyang, yeah, generally the cause for this kind of issue is not providing the correct path or relative path for configuration file.
